name: Release version

on:
  push:
    branches:
      - main
      - 'push-action/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.MASTER_PAT }}
          version-file: './version.json'
          fallback-version: 3.1.0
          git-push: false

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.MASTER_PAT }}
          branch: main
          tags: true
          unprotect_reviews: true


